plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - 2017-01-14-dont-worry-couldnt-work-nasa-funded-research-made-public-now.md
  - 2017-01-15-book-review-zero-to-one-by-peter-thiel-next-google.md
  - 2017-01-23-rakesh-sharma-humble-superhero-life-advice.md
  - 2017-01-27-can-talk-space-yes-no-listening.md
  - 2017-02-03-wifiradio-crossespenetratespass-wall-light-failsdoesnt.md
  - 2017-02-13-moon-looks-red-blood-moon-blood-red-moon-really.md
  - 2017-03-02-can-see-higher-dimensions-real-exist-4th-dimension.md
  - 2017-03-14-still-spending-hundred-dollars-thousands-rupees-ssl-get-free-now-letsencrypt-org.md
  - 2017-03-19-focus-important-aspect-life.md
  - 2017-03-23-choices-make-make-us.md
  - 2017-03-28-story-of-life-value.md
  - 2017-04-04-home-made-solar-system-with-plastic-balls-and-colours.md
  - 2017-04-24-experiment-solar-energy-solar-panel-works.md
  - 2017-04-24-gravity-newton-and-einstein-definition-demonstration.md
  - 2017-04-24-newtons-car-third-law-motion-rocket-principle.md
  - 2017-05-07-optics-light-and-its-behaviourproperties.md
  - 2017-05-08-stargazing-first-voyage-space.md
  - 2017-05-10-how-we-learn-the-approaches-specially-kids-part-1.md
  - 2017-05-11-learn-approaches-part2-learning-learn-active-learning.md
  - 2017-05-17-choosing-startup-team.md
  - 2017-05-17-innovation-linearslow-exponentialfast.md
  - 2017-05-17-starting-a-technical-startup.md
  - 2017-06-27-parenting-for-better-learnings.md
  - 2017-07-03-know-and-spread-intelligence.md
  - 2017-08-21-art-of-teaching.md
  - 2017-08-27-coffee-builds-you.md
  - 2017-08-29-discovery-growth-managing-innovation-projects.md
  - 2017-09-04-value-customer-stakeholders.md
  - 2017-09-10-registering-startup-india-free-part-1.md
  - 2017-09-18-registering-startup-india-free-part-1-target.md
  - 2017-10-01-why-there-are-no-mosquito-in-day-time-do-they-sleep.md
  - 2017-10-02-ball-floating-air-find-reasons.md
  - 2017-10-09-inventive-thinking-part-1-overview.md
  - 2018-03-11-photos-experiments-using-microscope-binocular-telescope-camera.md
  - 2018-03-31-cant-see-stars-daytime-earth.md
  - 2018-04-06-sciloo-now-a-startup-india-recognized-startup.md
  - 2018-04-23-art-and-science-of-coffee-making.md
  - 2018-05-04-sciloo-on-amazon-in.md
  - 2018-05-28-book-review-see-small-telescope-101-cosmic-wonders.md
  - 2018-05-30-free-research-papers-scihub.md
  - 2018-06-04-prolific-inventors-talk-one-inventor.md
  - 2018-06-24-startup-strategy.md
  - 2018-07-18-sciloo-caffe-nono-place-coffee-chocolate-lovers.md
  - 2018-07-19-sciloo-amazon-activate-builder-startup-program.md
  - 2018-12-09-story-of-business-sciloo-customer-or-selling.md
  - 2019-02-15-airbnb-data-science-team-experience-jeff-feng.md
  - 2019-02-15-model-based-learning.md
  - 2019-02-16-few-thoughts-on-origin-of-universe.md
  - 2019-02-17-annual-tax-filing-for-llp-in-india.md
  - 2019-02-17-microservices-part-1-basic-concepts.md
  - 2019-02-23-innovative-thinking.md
  - 2019-03-05-observation-research-and-study.md
  - 2019-03-31-experiment-generation-of-electricity-from-wind.md